### PR TITLE
👀 add partly support for izq.trio

### PR DESCRIPTION
**Pull request by JimmyKmi**
Add partly support for izq.solo
No Idea for any zone service support

### CODE REVIEW

**Review by al-one — APPROVED** [review]

**Comment by tianzhuang55** [comment]
Works well now but no zone function. Any plans to add? Thanks!

**Comment by JimmyKmi** [comment]
Due to limitations on the Mi Home platform, it is currently not possible to access partition information. Therefore, there should be no updates about izq solo and trio here (probably), and what we can do is only hope lies in the possibility of 子擎 developing a plugin that can be directly integrated with Home Assistant.

By the way... I am not an employee of 子擎. For specific information, you should inquire with the official sources.

**Comment by JimmyKmi** [comment]
> Works well now but no zone function. Any plans to add? Thanks!

Due to limitations on the Mi Home platform, it is currently not possible to access partition information. Therefore, there should be no updates about izq solo and trio here (probably), and what we can do is only hope lies in the possibility of 子擎 developing a plugin that can be directly integrated with Home Assistant.

By the way... I am not an employee of 子擎. For specific information, you should inquire with the official sources.

**Comment by ABUAIJUTIE** [comment]
> > Works well now but no zone function. Any plans to add? Thanks!
> 
> Due to limitations on the Mi Home platform, it is currently not possible to access partition information. Therefore, there should be no updates about izq solo and trio here (probably), and what we can do is only hope lies in the possibility of 子擎 developing a plugin that can be directly integrated with Home Assistant.
> 
> By the way... I am not an employee of 子擎. For specific information, you should inquire with the official sources.

I just found out zone service was added to this model on [Miot-Spec](https://home.miot-spec.com/spec/izq.sensor_occupy.trio)!
重大利好消息哈哈哈！

**Comment by JimmyKmi** [comment]
> > > Works well now but no zone function. Any plans to add? Thanks!
> > 
> > 
> > Due to limitations on the Mi Home platform, it is currently not possible to access partition information. Therefore, there should be no updates about izq solo and trio here (probably), and what we can do is only hope lies in the possibility of 子擎 developing a plugin that can be directly integrated with Home Assistant.
> > By the way... I am not an employee of 子擎. For specific information, you should inquire with the official sources.
> 
> I just found out zone service was added to these 2 models([Trio](https://home.miot-spec.com/spec/izq.sensor_occupy.trio) and [Solo](https://home.miot-spec.com/spec/izq.sensor_occupy.solo)) on Miot-Spec!! 重大好消息哈哈哈！

这是米家的数据，没有开放读写权限。

**Pull request merged**
