### PR TITLE
Add more control for petfeeder.fi1

### PR DESCRIPTION
**Pull request by Jezza34000**
Add exclusion for useless property :
 'outfood_num,outfood_id,contrycode,feddplan_string,factory_result'
I try many stuff but these are fixed and never change.

Add new control button action : 
'resetclean' => to reset the clean counter
'pet_food_out' => to serve one portion

Add more sensor property : 
'fault' => global fault feeder
'outletstatus' => top lid information open/close
'doorstatus' => food delivery door status open/close

Add 2 new actions : 
'key_stat' => lock/unlock top button on feeder
'indicator_light.on' => blue indicator light on/off

These two last action only work with 'number_properties' buton it should work as 'switch_properties'

modified_feeder

### CODE REVIEW

**Comment by Drealine** [comment]
Hi @Jezza34000 
Got a Petfeeder. Seems door status not working at all when serve food.
Did you get the same result as well ?

Drealine

**Comment by Jezza34000** [comment]
Hi @Drealine this is because of refresh rate.
The door status quickly change from 0 -> 1 -> 0

**Comment by Drealine** [comment]
Hm really strange because in log books of HA, the state not change from 0 to 1 and vice versa..

**Comment by Jezza34000** [comment]
Yes it is. Integration refresh rate is not engouh to get the state from PetFeeder. That mean it will always stay to 0.

**Comment by Drealine** [comment]
Ok @Jezza34000 , tk a lot for your answer.
There is no workaround ?

**Comment by Drealine** [comment]
Jezza, you're from France ahah.
Donc, est-ce que tu sais si il y a moyen de changer l'intervalle de rafraichissement ?
L'idée serait d'avoir cette info pour vérifier si la nourriture est bien distribuée ^^

**Comment by Drealine** [comment]
Même problème qui apparaît lorsque la porte est bloquée. As-tu constaté le soucis ? @Jezza34000

**Comment by Jezza34000** [comment]
The only way to know if found was correctly delivered is : 

Call_action_by
SIID 5
AIID 6

xxx@zbx:~$ miiocli genericmiot --ip 192.168.0.100 --token xxxxxxxxxxxxx call_action_by 5 6
Running command call_action_by
{'did': 'call-5-6', 'siid': 5, 'aiid': 6, 'code': 0, 'out': [{'piid': 12, 'value': '0,6,0,3,0,1,9,0,2,0,2,13,0,2,0,3,17,0,2,255,4,21,0,2,255'}]}

Value is : 
index, hour, minute, portions, status, .....
status : 0=> Executed and OK 255=> Avaiting for delivery

And i keep going in english because we are on an international website and everyone must understand  ;-)

**Comment by Drealine** [comment]
I'm totally agree with that @Jezza34000, sorry for the inconvenient!

This is a solution, tk :) 
But I control my petfeeder with some automations directly in Home Assistant. I think it's directly on the firmware that Xiaomi can change this value to be persistent no ?

**Comment by Drealine** [comment]
For your PR, the repo tell that we can customize sensors and add more. Do you see that ?
Directly on the integration with HA. Just add a new integration and select customize :)

**Comment by Jezza34000** [comment]
I'm looking a way to add this feature as well. I think it's need more developement.
About the "door status" sesnsor i think it's just crap setting (same as outfood-num & feeding-measure)
For my PR it's based from the "sensors customizations" i've try many and many stuff and i think i have the best result for more control/sensors.

**Comment by Drealine** [comment]
Yes I think too. I'm know some base of python, I can help you if you want to do some tests :)
And agree with you, those sensors are need to be add in the panel device of HA.

**Pull request merged**
