### PR TITLE
Fix state issue for CGH1

### PR DESCRIPTION
**Pull request by lkisme**
State of CGH1 is wrong by default.

### CODE REVIEW

**Comment by al-one** [comment]
Are you sure that the state of [the device](https://home.miot-spec.com/spec/cgllc.magnet.hodor) returns the opposite ?

**Comment by lkisme** [comment]
I have only 1 device of this type, for me it does return the opposite state, and after the code change, the state display in HASS is right for me.
Maybe we can do some test on the original returned data from Xiaomi? or someone else who have CGH1 can confirm on this.

**Comment by al-one** [comment]
Can it be defined in [the file](https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/core/device_customizes.py) as a [custom attribute](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774) like `reverse_state` ?
```python
{
    'cgllc.magnet.hodor': {
        'reverse_state': True
    }
}
```

**Comment by lkisme** [comment]
You mean to implement this customization option? or this option is available already?
Indeed this would be more elegant.

**Comment by al-one** [comment]
This option does not exist, it would be great if you could implement it.

**Comment by lkisme** [comment]
Done

**Comment by al-one** [comment]
Thinks !

**Pull request merged**
