### PR TITLE
 add viomi.waterheater.u8 philips.light.moonlight

### PR DESCRIPTION
**Pull request by baiuu**

### CODE REVIEW

**Comment by hiyan** [comment]
I added the code for philips.light.moonlight to test... the min max temperature seems to limit to 3000 - 5700.

Specs for philips.light.moonlight is 1700 - 6500.

Side question, why is Mode and Current Color Mode not used?

**Comment by baiuu** [comment]
> I added the code for philips.light.moonlight to test... the min max temperature seems to limit to 3000 - 5700.
> 
> Specs for philips.light.moonlight is 1700 - 6500.
> 
> Side question, why is Mode and Current Color Mode not used?

this RP isn't fix all with philips.light.moonlight we will fix it

**Comment by baiuu** [comment]
> I added the code for philips.light.moonlight to test... the min max temperature seems to limit to 3000 - 5700.
> 
> Specs for philips.light.moonlight is 1700 - 6500.
> 
> Side question, why is Mode and Current Color Mode not used?

i will add new rp this rp close

**Comment by al-one** [comment]
@hiyan 

> the min max temperature seems to limit to 3000 - 5700. Specs for philips.light.moonlight is 1700 - 6500.

The final value sent to the device is a [percentage](https://github.com/rytilahti/python-miio/blob/17e713a559bdb63d38b544cdb3769bfef9af85b1/miio/integrations/light/philips/philips_moonlight.py#L188-L193).

----

> Side question, why is Mode and Current Color Mode not used?

Upgrade to master branch and try. If have bug, please create an issue for it.

**Comment by hiyan** [comment]
@al-one 
image

Light temp is not set if using UI slider if mireds > 580. Currently it will accept only up to 579. 

Everything else looks good. state_updater is showing Lan.

**Pull request closed without merging**
