### PR TITLE
feat: 增加小爱音箱通过url播放歌曲的服务

### PR DESCRIPTION
**Pull request by Heyxk**
增加一个小爱音箱通过url播放歌曲的服务, 可以配合nas使用

### CODE REVIEW

**Review by al-one — CHANGES_REQUESTED** [review]
感谢PR！
希望通过`MiotMediaPlayerEntity.play_media`来实现播放功能，可以参考：
https://github.com/al-one/hass-xiaomi-miot/blob/1bf6ab6994d6658dc86ed9196e69d2463a6d391b/custom_components/xiaomi_miot/media_player.py#L768-L781

**Review by al-one — APPROVED** [review]

**Comment by al-one** [comment]
```yaml
service: media_player.play_media
data:
  entity_id: media_player.xiaoai_x08c_d135
  media_content_type: music
  media_content_id: https://click33.gitee.io/xixi/bg.mp3
```
在我的小爱音响上执行后没有反应🤣。

2023-08-20 02:53:17.727 INFO (MainThread) [custom_components.xiaomi_miot.media_player] 客厅触屏小爱(xiaomi.wifispeaker.x08c): Play media: [{'deviceId': '297a063e-e604-4645-a8f2-b03f006c1c48', 'path': 'mediaplayer', 'method': 'player_play_url', 'message': '{"url": "https://click33.gitee.io/xixi/bg.mp3", "type": 1, "media": "app_ios"}'}, {'code': 0, 'message': "Msg has been successfully proxy to the device, this service is a simple proxy, if you encounter any problems pls contact ROM's developers directly!!!", 'data': {'code': 0}}]

**Comment by Heyxk** [comment]
> ```yaml
> service: media_player.play_media
> data:
>   entity_id: media_player.xiaoai_x08c_d135
>   media_content_type: music
>   media_content_id: https://click33.gitee.io/xixi/bg.mp3
> ```
> 
> 在我的小爱音响上执行后没有反应🤣。
> 
> 2023-08-20 02:53:17.727 INFO (MainThread) [custom_components.xiaomi_miot.media_player] 客厅触屏小爱(xiaomi.wifispeaker.x08c): Play media: [{'deviceId': '297a063e-xxxx-xxxx-xxxx-b03f006c1c48', 'path': 'mediaplayer', 'method': 'player_play_url', 'message': '{"url": "https://click33.gitee.io/xixi/bg.mp3", "type": 1, "media": "app_ios"}'}, {'code': 0, 'message': "Msg has been successfully proxy to the device, this service is a simple proxy, if you encounter any problems pls contact ROM's developers directly!!!", 'data': {'code': 0}}]


使用下面的格式在我的小爱音箱Pro上正常播放:
```yaml
service: media_player.play_media
data:
  media_content_id: https://click33.gitee.io/xixi/bg.mp3
  media_content_type: music
target:
  entity_id: media_player.xiaomi_lx06_3ec7_play_control
```

**Comment by lhy741059930** [comment]
```
service: media_player.play_media
data:
  media_content_id: https://click33.gitee.io/xixi/bg.mp3
  media_content_type: music
target:
  entity_id: media_player.xiaomi_l05c_11e2_play_control
```

以上服务执行之后我的小爱play 增强版没有反应。是否对小爱的版本有要求

**Comment by zhyueyueniao** [comment]
> 感谢PR！ 希望通过`MiotMediaPlayerEntity.play_media`来实现播放功能，可以参考：
> 
> https://github.com/al-one/hass-xiaomi-miot/blob/1bf6ab6994d6658dc86ed9196e69d2463a6d391b/custom_components/xiaomi_miot/media_player.py#L768-L781

大佬，你好，这个在我的小爱art可以正常播放，但是在小爱触屏版和智能家庭屏上什么反应都没有

**Comment by zhyueyueniao** [comment]
> ```yaml
> service: media_player.play_media
> data:
>   entity_id: media_player.xiaoai_x08c_d135
>   media_content_type: music
>   media_content_id: https://click33.gitee.io/xixi/bg.mp3
> ```
> 
> 在我的小爱音响上执行后没有反应🤣。
> 
> 2023-08-20 02:53:17.727 INFO (MainThread) [custom_components.xiaomi_miot.media_player] 客厅触屏小爱(xiaomi.wifispeaker.x08c): Play media: [{'deviceId': '297a063e-xxxx-xxxx-xxxx-b03f006c1c48', 'path': 'mediaplayer', 'method': 'player_play_url', 'message': '{"url": "https://click33.gitee.io/xixi/bg.mp3", "type": 1, "media": "app_ios"}'}, {'code': 0, 'message': "Msg has been successfully proxy to the device, this service is a simple proxy, if you encounter any problems pls contact ROM's developers directly!!!", 'data': {'code': 0}}]

大佬，你好，这个在我的小爱art可以正常播放，但是在小爱触屏版和智能家庭屏上也什么反应都没有

**Comment by haodadajipai** [comment]
> > ```yaml
> > service: media_player.play_media
> > data:
> >   entity_id: media_player.xiaoai_x08c_d135
> >   media_content_type: music
> >   media_content_id: https://click33.gitee.io/xixi/bg.mp3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在我的小爱音响上执行后没有反应🤣。
> > 2023-08-20 02:53:17.727 INFO (MainThread) [custom_components.xiaomi_miot.media_player] 客厅触屏小爱(xiaomi.wifispeaker.x08c): Play media: [{'deviceId': '297a063e-xxxx-xxxx-xxxx-b03f006c1c48', 'path': 'mediaplayer', 'method': 'player_play_url', 'message': '{"url": "https://click33.gitee.io/xixi/bg.mp3", "type": 1, "media": "app_ios"}'}, {'code': 0, 'message': "Msg has been successfully proxy to the device, this service is a simple proxy, if you encounter any problems pls contact ROM's developers directly!!!", 'data': {'code': 0}}]
> 
> 使用下面的格式在我的小爱音箱Pro上正常播放:
> 
> ```yaml
> service: media_player.play_media
> data:
>   media_content_id: https://click33.gitee.io/xixi/bg.mp3
>   media_content_type: music
> target:
>   entity_id: media_player.xiaomi_lx06_3ec7_play_control
> ```

大佬，最近不知道是更新了什么导致的，播放音乐会一直重复播放

**Comment by cccmder** [comment]
> > > ```yaml
> > > service: media_player.play_media
> > > data:
> > >   entity_id: media_player.xiaoai_x08c_d135
> > >   media_content_type: music
> > >   media_content_id: https://click33.gitee.io/xixi/bg.mp3
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 在我的小爱音响上执行后没有反应🤣。
> > > 2023-08-20 02:53:17.727 INFO (MainThread) [custom_components.xiaomi_miot.media_player] 客厅触屏小爱(xiaomi.wifispeaker.x08c): Play media: [{'deviceId': '297a063e-xxxx-xxxx-xxxx-b03f006c1c48', 'path': 'mediaplayer', 'method': 'player_play_url', 'message': '{"url": "https://click33.gitee.io/xixi/bg.mp3", "type": 1, "media": "app_ios"}'}, {'code': 0, 'message': "Msg has been successfully proxy to the device, this service is a simple proxy, if you encounter any problems pls contact ROM's developers directly!!!", 'data': {'code': 0}}]
> > 
> > 
> > 使用下面的格式在我的小爱音箱Pro上正常播放:
> > ```yaml
> > service: media_player.play_media
> > data:
> >   media_content_id: https://click33.gitee.io/xixi/bg.mp3
> >   media_content_type: music
> > target:
> >   entity_id: media_player.xiaomi_lx06_3ec7_play_control
> > ```
> 
> 大佬，最近不知道是更新了什么导致的，播放音乐会一直重复播放

我也是这个问题，之前用media_content_id指定音频链接，播放一次就自动停止了，现在会一直重复播放。我在node-red里的音频源是随机生成的，长度不定，导致也没办法手动停止，有点难受，相当于这个play_media的功能就完全没办法用了，大佬有解决办法不？

**Comment by haodadajipai** [comment]
> > > > ```yaml
> > > > service: media_player.play_media
> > > > data:
> > > >   entity_id: media_player.xiaoai_x08c_d135
> > > >   media_content_type: music
> > > >   media_content_id: https://click33.gitee.io/xixi/bg.mp3
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 在我的小爱音响上执行后没有反应🤣。
> > > > 2023-08-20 02:53:17.727 INFO (MainThread) [custom_components.xiaomi_miot.media_player] 客厅触屏小爱(xiaomi.wifispeaker.x08c): Play media: [{'deviceId': '297a063e-xxxx-xxxx-xxxx-b03f006c1c48', 'path': 'mediaplayer', 'method': 'player_play_url', 'message': '{"url": "https://click33.gitee.io/xixi/bg.mp3", "type": 1, "media": "app_ios"}'}, {'code': 0, 'message': "Msg has been successfully proxy to the device, this service is a simple proxy, if you encounter any problems pls contact ROM's developers directly!!!", 'data': {'code': 0}}]
> > > 
> > > 
> > > 使用下面的格式在我的小爱音箱Pro上正常播放:
> > > ```yaml
> > > service: media_player.play_media
> > > data:
> > >   media_content_id: https://click33.gitee.io/xixi/bg.mp3
> > >   media_content_type: music
> > > target:
> > >   entity_id: media_player.xiaomi_lx06_3ec7_play_control
> > > ```
> > 
> > 
> > 大佬，最近不知道是更新了什么导致的，播放音乐会一直重复播放
> 
> 我也是这个问题，之前用media_content_id指定音频链接，播放一次就自动停止了，现在会一直重复播放。我在node-red里的音频源是随机生成的，长度不定，导致也没办法手动停止，有点难受，相当于这个play_media的功能就完全没办法用了，大佬有解决办法不？

我直接放弃API的形式。直接解了SSH，用指令去播放了。如果你是PRO也可以看看这个拦截器：https://github.com/LGinC/xiaoai

拆机刷机看这个：https://github.com/duhow/xiaoai-patch/blob/master/research/lx06/install.md

**Comment by Heyxk** [comment]
很久没使用过这个了，目前不太清楚什么问题。
推荐给大家一个很棒的项目：[XiaoMusic: 无限听歌，解放小爱音箱](https://github.com/hanxi/xiaomusic)，使用小爱音箱播放音乐，音乐使用 yt-dlp 下载。

**Pull request merged**
